name: Release to PyPI

on:
  workflow_dispatch:
    inputs:
      test_pypi:
        description: 'Upload to Test PyPI instead of PyPI'
        required: false
        default: false
        type: boolean
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: python -m twine check dist/*

    - name: Upload to Test PyPI
      if: ${{ github.event.inputs.test_pypi == 'true' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true

    - name: Upload to PyPI
      if: ${{ github.event.inputs.test_pypi != 'true' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true

  smoke-test:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pipx
      run: python -m pip install --upgrade pip pipx

    - name: Wait for package availability
      run: |
        echo "Waiting for package to be available on PyPI..."
        sleep 60

    - name: Test pipx run micro-swe-agent --help (Test PyPI)
      if: ${{ github.event.inputs.test_pypi == 'true' }}
      run: pipx run --pip-args="--index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/" micro-swe-agent --help

    - name: Test pipx run micro-swe-agent --help (PyPI)
      if: ${{ github.event.inputs.test_pypi != 'true' }}
      run: pipx run micro-swe-agent --help

    - name: Test pip install and CLI commands (Test PyPI)
      if: ${{ github.event.inputs.test_pypi == 'true' }}
      run: |
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ micro-swe-agent
        micro --help
        micro-extra --help
        micro-e --help

    - name: Test pip install and CLI commands (PyPI)
      if: ${{ github.event.inputs.test_pypi != 'true' }}
      run: |
        pip install micro-swe-agent
        micro --help
        micro-extra --help
        micro-e --help